### ISSUE TITLE
Add it to awesome-mcp-servers

### ISSUE THREAD

**Issue by punkpeye** [amidabuddha/unichat-mcp-server#1]
Considering adding your tool to:

https://github.com/punkpeye/awesome-mcp-servers/

You can create a PR directly from README.md.

Just a suggestion!

**Comment by amidabuddha** [comment]
https://github.com/punkpeye/awesome-mcp-servers/pull/17

**Comment by amidabuddha** [comment]
Thank you, added

**Comment by amidabuddha** [comment]
https://github.com/punkpeye/awesome-mcp-servers/pull/17
